---
title: "Mississippi"
author: "Baily"
date: "`r Sys.Date()`" 
output: html_document
---

```{r setup, include=FALSE}
packages <- c("biscale", "car", "cleangeo", "cowplot", "geosphere", "maps",
"mapproj", "spatialreg", "spdep", "sf", "tidyverse","visreg")

library(spatialreg)

library(biscale)

sapply(packages, require, character.only=T)
#library(tidyverse)
data <- read.csv('https://raw.githubusercontent.com/chrismgentry/Spatial-Regression/master/Data/childpov18_southfull.csv',
colClasses = c("character", "character", "character",
"numeric", "numeric", "numeric", "numeric",
"numeric", "numeric", "numeric", "numeric",
"numeric", "numeric", "numeric", "numeric",
"numeric", "numeric", "numeric", "numeric",
"numeric", "numeric", "numeric", "numeric",
"numeric", "numeric", "numeric", "numeric",
"numeric", "numeric", "numeric", "numeric",
"numeric", "numeric", "numeric", "numeric"))
```

```{r}
names(data)[names(data)=="X2016.child.poverty"] <- "child.pov.2016"
ms_pov <- data %>% subset(State == "MS")
summary(ms_pov)

equation <- child.pov.2016 ~ rural + urban + lnmanufacturing + lnag +
lnretail + lnhealthss + lnconstruction + lnlesshs +
lnunemployment + lnsinglemom + lnblack + lnhispanic +
lnuninsured + lnincome_ratio + lnteenbirth + lnunmarried
options(scipen = 5)
```
```{r}
ols <- lm(equation, data=ms_pov)
summary(ols)
#library(maps)
fips <- county.fips
fips.codes <- separate(data = fips, col = polyname, into = c("state", "county"), sep = ",")
ms_fips <- subset(fips.codes, state=="texas", select=fips)
```

```{r}
#library(sf)
se_shp <- st_read(file.path("se_counties"))
ms_sf <- se_shp %>% subset(STATE_NAME == "Mississippi")
#library(spdep)
sf_use_s2(FALSE)
neighb.data <- poly2nb(ms_sf, queen=T)
cont.neighb <- nb2listw(neighb.data,style="W", zero.policy = TRUE)
lm.morantest(ols, cont.neighb)
lm.LMtests(ols, cont.neighb, test="all")
```

```{r}
#library(spatialreg)
SLX.model <- spatialreg::lmSLX(equation, data=ms_pov, cont.neighb)
summary(SLX.model)
summary(spatialreg::impacts(SLX.model, cont.neighb), zstats = TRUE)[["pzmat"]]
sp.lag.model <- spatialreg::lagsarlm(equation, data=ms_pov, cont.neighb)
```

```{r}
summary(sp.lag.model, Nagelkerke = TRUE)
summary(spatialreg::impacts(sp.lag.model, listw = cont.neighb, R=100), zstats = TRUE)[["pzmat"]]
sp.err.model <- spatialreg::errorsarlm(equation, data=ms_pov, cont.neighb)
```

```{r}
summary(sp.err.model, Nagelkerke = TRUE)
spatialreg::Hausman.test(sp.err.model)
sd.err <- spatialreg::errorsarlm(equation, ms_pov, cont.neighb, etype = "emixed")
sdm <- spatialreg::lagsarlm(equation, ms_pov, cont.neighb, type = "mixed")
```

```{r}
summary(sd.err, Nagelkerke = TRUE)
summary(spatialreg::impacts(sd.err, listw = cont.neighb, R = 100), zstats = TRUE)[["pzmat"]]
spatialreg::LR.Sarlm(sd.err,sp.err.model)
ms.xy <- st_centroid(ms_sf)
```

```{r}
#Create neighbors
all.dist.k1 <- knn2nb(knearneigh(ms.xy, k=1, longlat = TRUE))
all.dist.k3 <- knn2nb(knearneigh(ms.xy, k=3, longlat = TRUE))
all.dist.k5 <- knn2nb(knearneigh(ms.xy, k=5, longlat = TRUE))
```

```{r}
#Determine max k distance value to neighbor
all.max.k1 <- max(unlist(nbdists(all.dist.k1, ms.xy, longlat=TRUE)))
all.max.k3 <- max(unlist(nbdists(all.dist.k3, ms.xy, longlat=TRUE)))
all.max.k5 <- max(unlist(nbdists(all.dist.k5, ms.xy, longlat=TRUE)))
```

```{r}
#Calculate neighbors based on distance
all.sp.dist.k1 <- dnearneigh(ms.xy, d1=0, d2=1 * all.max.k1, longlat = TRUE)
all.sp.dist.k3 <- dnearneigh(ms.xy, d1=0, d2=1 * all.max.k3, longlat = TRUE)
all.sp.dist.k5 <- dnearneigh(ms.xy, d1=0, d2=1 * all.max.k5, longlat = TRUE)
```

```{r}
#Create neighbor list
all.dist.neighb.k1 <- nb2listw(all.sp.dist.k1,style="W", zero.policy = TRUE)
all.dist.neighb.k3 <- nb2listw(all.sp.dist.k3,style="W", zero.policy = TRUE)
all.dist.neighb.k5 <- nb2listw(all.sp.dist.k5,style="W", zero.policy = TRUE)
all.dist.lag.k1 <- spatialreg::lagsarlm(equation, data = ms_pov, listw = all.dist.neighb.k1)
all.dist.lag.k3 <- spatialreg::lagsarlm(equation, data = ms_pov, listw = all.dist.neighb.k3)
all.dist.lag.k5 <- spatialreg::lagsarlm(equation, data = ms_pov, listw = all.dist.neighb.k5)
```

```{r}
summary(all.dist.lag.k1, Nagelkerke = TRUE)
```

```{r}
all.dist.err.k1 <- spatialreg::errorsarlm(equation, data = ms_pov, listw = all.dist.neighb.k1)
all.dist.err.k3 <- spatialreg::errorsarlm(equation, data = ms_pov, listw = all.dist.neighb.k3)
all.dist.err.k5 <- spatialreg::errorsarlm(equation, data = ms_pov, listw = all.dist.neighb.k5)
```

```{r}
summary(all.dist.err.k1, Nagelkerke = TRUE)
dist.err.data <- summary(all.dist.err.k1, correlation=TRUE, Nagelkerke = TRUE)
dist.err.output <- cbind.data.frame(ms_pov$FIPS,
dist.err.data$fitted.values,
dist.err.data$residual,
ms_pov$child.pov.2016,
ms_pov$lnsinglemom,
ms_pov$lnuninsured,
ms_pov$lnlesshs,
ms_pov$lnincome_ratio,
stringsAsFactors = FALSE)
```


```{r}
#Renaming columns
colnames(dist.err.output) <- c("fips","fitted","resid","childpov",
"single_mom","uninsured","less_hs","income_ratio")
ms_poly <- merge(x = ms_sf, y = dist.err.output,
by.x = "FIPS", by.y = "fips", all = TRUE)
```

```{r}
#library(biscale)
bivariate_data <- bi_class(ms_poly, x = childpov, y = single_mom,
dim = 3, style = "quantile")
legend <- bi_legend(pal = "DkViolet",
dim = 3,
xlab = "Child Poverty",
ylab = "Single Mother¥n Households",
size = 6)
```

```{r}
world <- map_data("world")
states <- map_data("state")
southern_states <- subset(states, region %in%
c("texas", "arkansas", "louisiana", "mississippi",
"alabama", "georgia", "florida", "north carolina",
"south carolina", "tennessee", "oklahoma",
"kentucky", "west virginia", "virginia",
"maryland", "delaware", "district of columbia"))
```


```{r}
mom_pov_map <- ggplot() +
geom_polygon(data = world, aes(x=long,y=lat, group=group), fill = "gray95", color = "white") +
geom_polygon(data = states, aes(x=long,y=lat, group=group), fill = "gray", color = "white") +
geom_polygon(data = southern_states, aes(x=long,y=lat, group=group), fill = NA, size = 0.01, color = "white") +
geom_sf(data = bivariate_data, aes(fill = bi_class), color = "grey50", show.legend = FALSE) +
bi_scale_fill(pal = "DkViolet", dim = 3) +
coord_sf(crs = 4326, xlim=c(-92,-87), ylim=c(28,40)) +
theme_void() + theme(legend.title.align=0.5) +
theme(panel.background = element_rect(fill = 'deepskyblue'),
panel.grid.major = element_line(colour = NA)) +
labs(x = "Longitude", y = "Latitude", fill = "Child Poverty",
title = "Bivariate Map of Child Poverty and Single Mother Households") +
theme(plot.title = element_text(face = "bold", hjust = 0.5))
mom_pov_map
```

```{r}
#library(cowplot)
final_map <- ggdraw() +
draw_plot(mom_pov_map, 0, 0, 1, 1) +
draw_plot(legend, 0.60, 0.035, 0.25, 0.25)
final_map
```

